rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - cla/google
    - Test AWK Script
    - Lint with black
    - Test with pytest